# Base Stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
COPY *.csproj .
RUN dotnet restore

# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/ .
WORKDIR "/src/Club.Webapi"
CMD ["dotnet", "watch", "run", "--no-launch-profile"]